name: bwu_model
version: 0.0.1
description: A sample web application
author: Günter Zöchbauer <guenter@gzoechbauer.com>
publish-to: none
environment:
  sdk: ">=1.9.0-dev <2.0.0"

dependencies:
  args: any
  browser: any
  bwu_server:
    path: ../bwu_server
  bwu_datagrid: any
  bwu_polymer_routing: any
  core_elements: any
  di: any
  googleapis_auth: any
  logging: any
  logging_handlers: any
  paper_elements: any
  polymer: any
  quiver: any
  quiver_log: any
  smoke: any

dependency_overrides:
  analyzer: any
  googleapis_beta: ^0.6.0
  quiver: ^0.20.0
  uuid: ^0.5.0

dev_dependencies:
  unittest: any

transformers:
- polymer:
    entry_points:
    - web/index.html
- di

- $dart2js:
    $exclude: bin/**.dart
